---
name: Test

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: ℹ️ Examine Dir
        run: ls googlebackup/googlebackup
      - name: ℹ️ Add Google client_secret.json
        run: printf ${{ secrets.GOOGLE_CLIENT_SECRET }} > googlebackup/googlebackup/client_secret.json
      - name: ℹ️ Examine Dir Again
        run: ls googlebackup/googlebackup
      - name: ℹ️ Examine File
        run: cat googlebackup/googlebackup/client_secret.json
